apiVersion: batch/v1
kind: Job
metadata:
  name: demo
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: container1
        image: ubuntu
        command: ["sh", "-c", "for i in `seq 1 10`; do echo $i; sleep 1; done"]
