apiVersion: batch/v1
kind: Job
metadata:
  name: demo
spec:
  template:
    spec:
      containers:
      - name: container1
        image: ubuntu
        command: ["sh", "-c", "for i in `seq 1 10`; do echo $i; sleep 1; done"]
      - name: container2
        image: ubuntu
        command: ["sh", "-c", "for i in `seq 11 20`; do echo $i; sleep 1; done"]
      restartPolicy: Never
      backoffLimit: 0
